In [1]:
import os

import pandas as pd
from tqdm import tqdm

In [2]:
PARQUET_DF_PATH = './data/original_data/competition_data_final.parquet'

parquet_parts = list(set(os.listdir(PARQUET_DF_PATH)) - set(['_SUCCESS']))
parquet_parts

['part-00000-aba60f69-2b63-4cc1-95ca-542598094698-c000.snappy.parquet',
 'part-00008-aba60f69-2b63-4cc1-95ca-542598094698-c000.snappy.parquet',
 'part-00007-aba60f69-2b63-4cc1-95ca-542598094698-c000.snappy.parquet',
 'part-00001-aba60f69-2b63-4cc1-95ca-542598094698-c000.snappy.parquet',
 'part-00005-aba60f69-2b63-4cc1-95ca-542598094698-c000.snappy.parquet',
 'part-00006-aba60f69-2b63-4cc1-95ca-542598094698-c000.snappy.parquet',
 'part-00009-aba60f69-2b63-4cc1-95ca-542598094698-c000.snappy.parquet',
 'part-00004-aba60f69-2b63-4cc1-95ca-542598094698-c000.snappy.parquet',
 'part-00002-aba60f69-2b63-4cc1-95ca-542598094698-c000.snappy.parquet',
 'part-00003-aba60f69-2b63-4cc1-95ca-542598094698-c000.snappy.parquet']

In [ ]:
df = pd.read_parquet(os.path.join(PARQUET_DF_PATH, 'part-00000-aba60f69-2b63-4cc1-95ca-542598094698-c000.snappy.parquet'))

In [17]:
df.head()

,region_name,city_name,cpe_manufacturer_name,cpe_model_name,url_host,cpe_type_cd,cpe_model_os_type,price,date,part_of_day,request_cnt,user_id
0,Краснодарский край,Краснодар,Apple,iPhone 7,ad.adriver.ru,smartphone,iOS,20368.0,2022-06-15,morning,1,45098
1,Краснодарский край,Краснодар,Apple,iPhone 7,apple.com,smartphone,iOS,20368.0,2022-06-19,morning,1,45098
2,Краснодарский край,Краснодар,Apple,iPhone 7,avatars.mds.yandex.net,smartphone,iOS,20368.0,2022-06-12,day,1,45098
3,Краснодарский край,Краснодар,Apple,iPhone 7,googleads.g.doubleclick.net,smartphone,iOS,20368.0,2022-05-16,day,1,45098
4,Краснодарский край,Краснодар,Apple,iPhone 7,googleads.g.doubleclick.net,smartphone,iOS,20368.0,2022-05-30,day,1,45098

In [10]:
number_only_urls = set()

for el in tqdm(df['url_host']):
    if set(el) <= set('0123456789'):
        number_only_urls.add(el)

100%|██████████| 32156858/32156858 [00:56<00:00, 573986.18it/s]

In [17]:
len(number_only_urls)  # note: it's only from one partition

65

In [16]:
list(number_only_urls)[:10]

['40', '34', '16', '43', '33', '19', '12', '59', '15', '127']

In [14]:
df[df['url_host'] == '1'].head()

,region_name,city_name,cpe_manufacturer_name,cpe_model_name,url_host,cpe_type_cd,cpe_model_os_type,price,date,part_of_day,request_cnt,user_id
176834,Ростовская область,Ростов-на-Дону,Samsung,Galaxy A50 Dual,1,smartphone,Android,16408.0,2021-07-21,morning,1,341280
177211,Свердловская область,Екатеринбург,Samsung,Galaxy A50 Dual,1,smartphone,Android,16408.0,2021-06-19,evening,1,341280
359564,Республика Татарстан,Казань,Samsung,Galaxy J6 Plus Dual,1,smartphone,Android,2390.0,2021-07-08,day,1,142005
359763,Республика Татарстан,Казань,Samsung,Galaxy J6 Plus Dual,1,smartphone,Android,2390.0,2021-07-08,morning,1,142005
359808,Республика Татарстан,Казань,Samsung,Galaxy J6 Plus Dual,1,smartphone,Android,2390.0,2021-07-06,evening,1,142005

In [16]:
# public_train = pd.read_parquet('data/original_data/public_train.parquet')

In [6]:
# public_train.head()

         age is_male  user_id
350459  31.0       1   350459
188276  35.0       1   188276
99002   41.0       0    99002
155506  33.0       0   155506
213873  54.0       0   213873

In [1]:
def is_punycode(s: str) -> bool:
    return s.startswith('xn--')
    
    
def convert_punycode(puny_domain: str) -> str:
    """
    Converts punycode to unicode

    Example:
    >>> convert_punycode('xn--22-glcqfm3bya1b.xn--p1ai')
    <<< 'грузчик22.рф'
    """
    return puny_domain.encode().decode('idna')

In [3]:
s = 'xn--22-glcqfm3bya1b.xn--p1ai'
if is_punycode(s):
    s = convert_punycode(s)
s

'грузчик22.рф'

In [1]:
import pandas as pd

In [13]:
df = pd.read_parquet('data/competition_data_edges.parquet')

In [14]:
df = df.rename(columns = {'url_host_preprocesed': '_orig_url_host_preprocesed'})

In [15]:
df.head()

   user_id _orig_url_host_preprocesed  request_cnt
0   359133        campaign.aliexpress            4
1    95893                 m.facebook            1
2   193478              avr.i-trailer            5
3   348061                     e.mail            9
4   316468            sun9-32.userapi           10

In [16]:
df_item_map = pd.read_csv('data/url_host_preprocesed_mapping.csv')

In [17]:
df_item_map.head()

  _orig_url_host_preprocesed  url_host_preprocesed
0    googleads.g.doubleclick                     2
1                     yandex                     3
2                    i.ytimg                     4
3                         vk                     5
4         avatars.mds.yandex                     6

In [19]:
new_df = df.merge(df_item_map, on=['_orig_url_host_preprocesed'])

In [21]:
new_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31740362 entries, 0 to 31740361
Data columns (total 4 columns):
 #   Column                      Dtype
---  ------                      -----
 0   user_id                     int64
 1   _orig_url_host_preprocesed  object
 2   request_cnt                 int64
 3   url_host_preprocesed        int64
dtypes: int64(3), object(1)
memory usage: 968.6+ MB

In [22]:
new_df.isnull().values.any()

False

In [23]:
new_df.head()

   user_id _orig_url_host_preprocesed  request_cnt  url_host_preprocesed
0   359133        campaign.aliexpress            4                    82
1   126106        campaign.aliexpress            1                    82
2    88824        campaign.aliexpress            1                    82
3   172313        campaign.aliexpress            1                    82
4   405304        campaign.aliexpress            1                    82

In [24]:
new_df['url_host_preprocesed'].max()

196694

In [2]:
import pandas as pd

In [3]:
age_target_df = pd.read_csv('./data/train_age.csv')

In [6]:
age_target_df['age'].value_counts()

age
2    87270
3    77486
4    42442
1    32641
5    23580
6     5503
Name: count, dtype: int64

In [8]:
age_target_df['age'].value_counts().max() / len(age_target_df)

0.3245178899457835

In [9]:
gender_target_df = pd.read_csv('./data/train_gender.csv')

In [12]:
gender_target_df['is_male'].value_counts()

is_male
1    135332
0    128994
Name: count, dtype: int64

In [5]:
!ls

bin				     lightning_logs
checkpoints			     make_dataset.py
conf				     make_graph.py
create_aggregated_edges.py	     make_url_embedding_outdated.py
create_embedding_tensors.ipynb	     make-url-embeddings.ipynb
create_subdataset_for_debug.ipynb    models
data				     outputs
embeddings_validation_age.work	     playground.ipynb
embeddings_validation_gender.work    preprocess_dataset.py
embeddings_validation_template.yaml  README.md
get_urls.py			     results
hydra_outputs

In [1]:
import os

import torch
from tqdm import tqdm

In [2]:
import pandas as pd

In [47]:
TRAIN_PTLS_PARQUET_PATH = 'data/train_trx_file.parquet'
TEST_PTLS_PARQUET_PATH = 'data/test_trx_file.parquet'

In [48]:
train_partition_paths = [os.path.join(TRAIN_PTLS_PARQUET_PATH, f) for f in os.listdir(TRAIN_PTLS_PARQUET_PATH) if f.endswith('.parquet')]
test_partition_paths = [os.path.join(TEST_PTLS_PARQUET_PATH, f) for f in os.listdir(TEST_PTLS_PARQUET_PATH) if f.endswith('.parquet')]

In [67]:
from typing import List


def check_users_with_repeating_time_exist(partition_paths: List[str]) -> bool:
    for partition_path in tqdm(partition_paths):
        df = pd.read_parquet(partition_path)
        for event_times_of_a_user in df['event_time'].values:
            if len(event_times_of_a_user) != set(event_times_of_a_user):
                return True
    return False


check_users_with_repeating_time_exist(train_partition_paths)

  0%|          | 0/800 [00:00<?, ?it/s]

True

In [49]:
train_all_unique_url_ids = set()
for train_partition_path in tqdm(train_partition_paths):
    df = pd.read_parquet(train_partition_path)
    for urls_of_a_user in df['url_host_preprocesed'].values:
        train_all_unique_url_ids.update(urls_of_a_user)

100%|██████████| 800/800 [00:35<00:00, 22.41it/s]

In [50]:
test_all_unique_url_ids = set()
for test_partition_path in tqdm(test_partition_paths):
    df = pd.read_parquet(test_partition_path)
    for urls_of_a_user in df['url_host_preprocesed'].values:
        test_all_unique_url_ids.update(urls_of_a_user)

100%|██████████| 400/400 [00:03<00:00, 102.99it/s]

In [51]:
max(train_all_unique_url_ids)

196694

In [52]:
max(test_all_unique_url_ids)

196692

In [11]:
set.union(train_all_unique_url_ids, test_all_unique_url_ids) <= set(range(2, 196695))

True

In [53]:
url_encoding_map_df = pd.read_csv('data/url_host_preprocesed_mapping.csv')

In [54]:
all_encodings = url_encoding_map_df['url_host_preprocesed']

In [55]:
set(all_encodings) == set(range(2, 196695))

True

In [56]:
set(all_encodings) == set.union(train_all_unique_url_ids, test_all_unique_url_ids)

False

In [57]:
abscent_urls = set(all_encodings) - set.union(train_all_unique_url_ids, test_all_unique_url_ids)

In [58]:
len(abscent_urls)

1801

In [59]:
abscent_urls

{196609,
 155650,
 163844,
 139279,
 139280,
 163859,
 147476,
 172051,
 180251,
 147484,
 114717,
 155678,
 196639,
 139296,
 196642,
 163878,
 139303,
 155692,
 122951,
 172108,
 147533,
 163934,
 122985,
 163945,
 163950,
 139385,
 139386,
 163965,
 155775,
 155782,
 172167,
 180363,
 147599,
 139419,
 155808,
 131233,
 147620,
 172198,
 131247,
 155835,
 131263,
 139459,
 147653,
 164039,
 172233,
 147661,
 155858,
 106711,
 155868,
 139489,
 180452,
 180460,
 155891,
 155903,
 155905,
 164105,
 147725,
 139537,
 164115,
 139540,
 147745,
 139559,
 180520,
 188711,
 164138,
 155953,
 139575,
 180541,
 180547,
 155974,
 147784,
 147787,
 180560,
 180563,
 115032,
 139612,
 188779,
 147825,
 139644,
 131457,
 115076,
 139658,
 188810,
 188818,
 147859,
 164250,
 172443,
 131485,
 180637,
 164255,
 164256,
 156066,
 131504,
 156084,
 131511,
 188858,
 172498,
 115160,
 115177,
 147951,
 147953,
 156146,
 172531,
 188922,
 147966,
 139784,
 147976,
 131594,
 180745,
 139791,
 188943,
 156189,
 131614,
 107039,
 164383,
 156195,
 139816,
 148008,
 188968,
 164399,
 148019,
 139832,
 148025,
 148027,
 180796,
 172613,
 148043,
 189007,
 148048,
 172625,
 180817,
 131675,
 139867,
 189025,
 139877,
 139880,
 172667,
 115327,
 131712,
 189055,
 164483,
 107140,
 139910,
 180879,
 139921,
 164500,
 172694,
 172703,
 156320,
 172727,
 139963,
 172733,
 180926,
 164545,
 180951,
 156381,
 58079,
 156391,
 123630,
 148207,
 131828,
 189174,
 189176,
 189178,
 115453,
 148221,
 107263,
 156413,
 164607,
 164610,
 172800,
 189192,
 148233,
 172810,
 164620,
 99093,
 189208,
 156444,
 140065,
 107306,
 181037,
 164654,
 172848,
 189236,
 123701,
 123707,
 140092,
 189245,
 156479,
 189254,
 123727,
 140115,
 181075,
 140122,
 107360,
 140130,
 148326,
 115559,
 181096,
 181098,
 156527,
 164720,
 172913,
 140146,
 172915,
 189302,
 172924,
 140164,
 156554,
 107423,
 181151,
 172969,
 189356,
 156591,
 189375,
 148422,
 181206,
 115678,
 148449,
 173030,
 173037,
 156658,
 164850,
 164851,
 115729,
 132113,
 164881,
 181269,
 189462,
 156706,
 173094,
 173099,
 99372,
 156716,
 156724,
 173110,
 173112,
 164923,
 115772,
 181308,
 189507,
 189509,
 189515,
 123982,
 140371,
 140373,
 156757,
 140380,
 124000,
 148588,
 148599,
 124025,
 140421,
 140425,
 165001,
 140428,
 173203,
 148630,
 165020,
 173212,
 181412,
 189605,
 140458,
 148651,
 189628,
 148675,
 181446,
 181452,
 173264,
 173266,
 148693,
 115928,
 140504,
 189666,
 148716,
 124148,
 173301,
 189689,
 189696,
 156936,
 173320,
 148748,
 140566,
 173337,
 173339,
 156957,
 50469,
 140584,
 165160,
 140589,
 173357,
 181567,
 156992,
 189763,
 107853,
 66899,
 140628,
 181587,
 181591,
 165210,
 66911,
 132456,
 132461,
 189809,
 181625,
 181634,
 165251,
 116103,
 173454,
 157076,
 165271,
 140702,
 189855,
 173473,
 181665,
 148900,
 157096,
 173482,
 165298,
 140734,
 173504,
 157128,
 165320,
 157137,
 173523,
 173524,
 181722,
 165340,
 181733,
 181739,
 157169,
 157171,
 165364,
 148981,
 140797,
 140802,
 157192,
 140809,
 165388,
 189968,
 116246,
 149027,
 173603,
 189993,
 157234,
 181812,
 181813,
 108106,
 149077,
 157274,
 91743,
 140901,
 173673,
 165487,
 124534,
 108156,
 149118,
 157327,
 124577,
 181925,
 149158,
 157354,
 149163,
 149174,
 190136,
 190159,
 190172,
 173793,
 141029,
 190184,
 165612,
 116461,
 182005,
 173814,
 173819,
 141052,
 182011,
 108305,
 157462,
 149286,
 157486,
 157494,
 165689,
 182085,
 165704,
 190285,
 100177,
 141146,
 157536,
 149346,
 149377,
 149378,
 182158,
 173973,
 190360,
 141222,
 149419,
 182187,
 141231,
 133040,
 149431,
 182204,
 190401,
 190404,
 182216,
 190409,
 190412,
 182222,
 165840,
 141277,
 157661,
 141292,
 124911,
 182260,
 149501,
 141311,
 174087,
 190472,
 149533,
 182302,
 149543,
 190504,
 174123,
 190509,
 174128,
 149556,
 165946,
 116795,
 141374,
 165950,
 165960,
 174154,
 182364,
 190558,
 165983,
 174179,
 141412,
 141414,
 165992,
 141425,
 190577,
 174203,
 141436,
 125053,
 67715,
 157832,
 75913,
 190609,
 166036,
 174236,
 92324,
 141478,
 166058,
 174254,
 75956,
 149702,
 149712,
 100579,
 166115,
 92391,
 174325,
 133368,
 190715,
 182527,
 125185,
 157955,
 141577,
 182537,
 125197,
 157966,
 157969,
 190743,
 141594,
 182559,
 108832,
 92450,
 141607,
 166184,
 182575,
 141619,
 190776,
 182593,
 158022,
 166216,
 149840,
 190800,
 158036,
 174421,
 174424,
 166237,
 100713,
 141680,
 141681,
 166260,
 158069,
 149880,
 166264,
 182648,
 182654,
 125322,
 174479,
 158103,
 166298,
 158124,
 174509,
 149935,
 133555,
 141748,
 166324,
 190906,
 117181,
 108999,
 141773,
 149971,
 59861,
 182747,
 125409,
 174562,
 166374,
 158183,
 141801,
 141807,
 158192,
 141812,
 117240,
 51708,
 166403,
 190988,
 190990,
 141842,
 174615,
 158232,
 191004,
 158249,
 191019,
 191035,
 141885,
 158275,
 182853,
 166491,
 141936,
 150132,
 174711,
 166524,
 166526,
 191107,
 141959,
 150159,
 191125,
 166559,
 174753,
 182951,
 117420,
 174765,
 182964,
 174777,
 166586,
 174783,
 125634,
 133826,
 150214,
 117447,
 182983,
 150217,
 150219,
 142034,
 142035,
 166618,
 166624,
 150242,
 150244,
 191214,
 166642,
 183033,
 142077,
 125696,
 166664,
 133902,
 150291,
 117524,
 166679,
 166684,
 158493,
 158501,
 142126,
 117560,
 142138,
 150333,
 174912,
 158533,
 191322,
 183131,
 174944,
 142180,
 174952,
 174954,
 142196,
 150388,
 166778,
 174970,
 158591,
 158595,
 101258,
 142218,
 142224,
 174992,
 134038,
 183210,
 175024,
 175029,
 183223,
 134073,
 175049,
 191434,
 93145,
 150492,
 125921,
 142305,
 191463,
 142312,
 183272,
 158703,
 183294,
 166919,
 158732,
 117776,
 191511,
 191512,
 191514,
 175133,
 166950,
 166951,
 158768,
 191539,
 183353,
 183362,
 158794,
 142412,
 183376,
 150609,
 166993,
 150622,
 191596,
 191607,
 158842,
 126077,
 183423,
 117888,
 158870,
 142488,
 117921,
 183458,
 167083,
 183468,
 158899,
 126139,
 158907,
 158916,
 183495,
 191701,
 150743,
 126175,
 101603,
 183532,
 134381,
 175341,
 126202,
 191743,
 118025,
 167180,
 142607,
 175396,
 150833,
 159025,
 183601,
 175433,
 126287,
 85330,
 150867,
 142692,
 167271,
 191847,
 118123,
 159087,
 191864,
 150908,
 150912,
 159106,
 167304,
 159115,
 183693,
 159120,
 142737,
 142742,
 175513,
 159133,
 134558,
 150942,
 183709,
 126378,
 150961,
 126392,
 183736,
 159163,
 93628,
 191935,
 167360,
 142785,
 175558,
 126408,
 126410,
 167370,
 183755,
 183765,
 159193,
 167386,
 167396,
 151014,
 151018,
 167402,
 191982,
 175603,
 191988,
 167419,
 175613,
 167422,
 191998,
 183810,
 159237,
 151047,
 167434,
 159243,
 175628,
 183820,
 175633,
 142868,
 142873,
 142878,
 192031,
 167456,
 183843,
 142897,
 183870,
 167492,
 126535,
 167497,
 151118,
 159312,
 142933,
 183906,
 159331,
 142951,
 134765,
 142970,
 151163,
 110205,
 126590,
 183940,
 142984,
 192139,
 175761,
 110232,
 151193,
 110238,
 143007,
 151199,
 167591,
 183976,
 192168,
 134829,
 143023,
 183989,
 159417,
 192186,
 175807,
 175811,
 143049,
 192208,
 85718,
 143067,
 93918,
 143070,
 167648,
 151265,
 184036,
 175855,
 36598,
 175867,
 184072,
 175882,
 143115,
 126735,
 159513,
 175897,
 159519,
 159520,
 151338,
 175917,
 175925,
 159554,
 167748,
 192327,
 159561,
 102218,
 151371,
 175950,
 159569,
 192343,
 151387,
 159580,
 159583,
 175969,
 192355,
 143212,
 175982,
 192370,
 184180,
 184183,
 143227,
 143230,
 184206,
 176016,
 192400,
 159643,
 159649,
 167841,
 192421,
 176038,
 192424,
 192437,
 192446,
 143301,
 159697,
 151506,
 167892,
 159705,
 167899,
 126942,
 143327,
 184291,
 143332,
 151527,
 184299,
 143344,
 176119,
 151545,
 167929,
 159744,
 192513,
 143362,
 86021,
 176137,
 118794,
 143373,
 135189,
 184344,
 176162,
 143396,
 159785,
 176169,
 192557,
 192559,
 176177,
 192567,
 151608,
 192574,
 118849,
 168001,
 192585,
 168018,
 159830,
 192600,
 151649,
 159842,
 159844,
 192612,
 127080,
 143464,
 168040,
 168042,
 143474,
 143475,
 192628,
 143485,
 143486,
 168061,
 176255,
 192639,
 69763,
 192643,
 151689,
 184477,
 151721,
 159915,
 184496,
 143543,
 151736,
 192696,
 151738,
 192697,
 94396,
 184512,
 184513,
 184517,
 168137,
 184524,
 192716,
 176338,
 86228,
 135394,
 192740,
 151781,
 168168,
 143594,
 159981,
 192772,
 143629,
 168207,
 184592,
 168218,
 176416,
 184611,
 184617,
 151854,
 184628,
 143682,
 94533,
 69960,
 143691,
 61784,
 160100,
 176488,
 94571,
 160113,
 143730,
 168305,
 168318,
 151936,
 184704,
 151942,
 151943,
 184714,
 143757,
 168344,
 192931,
 151972,
 135593,
 160181,
 151991,
 184760,
 176569,
 168378,
 192961,
 152010,
 176590,
 184782,
 111057,
 168407,
 176600,
 135644,
 160221,
 184808,
 152041,
 168425,
 168429,
 160239,
 143857,
 152054,
 176630,
 143867,
 184838,
 152073,
 168458,
 184842,
 193059,
 184868,
 176679,
 143912,
 160310,
 152119,
 184891,
 152128,
 70222,
 168530,
 176722,
 193110,
 184926,
 160352,
 152162,
 160361,
 168580,
 152208,
 176785,
 94875,
 152219,
 176798,
 168608,
 144033,
 111273,
 176811,
 ...}

In [60]:
url_encoding_map_df[url_encoding_map_df['url_host_preprocesed'].isin(abscent_urls)]

       _orig_url_host_preprocesed  url_host_preprocesed
22704             dot.lipetsk-lmk                 22706
36596            kostroma.restate                 36598
39320            ulan-ude.restate                 39322
48290                 irkutsk.vsn                 48292
50467                perm.novobyt                 50469
...                           ...                   ...
196453                polezno4you                196455
196561                 vyazma.vsn                196563
196607               morendi-ural                196609
196637                   pkuint26                196639
196640                      p-rul                196642

[1801 rows x 2 columns]

In [19]:
url_host_embeddings_ptls_ids = torch.load('data/url_host_embeddings_ptls_ids.pt')

In [20]:
url_host_embeddings_ptls_ids.shape

torch.Size([196695, 256])

In [21]:
zeros_row = torch.zeros(url_host_embeddings_ptls_ids.shape[1])

In [22]:
# нулевые эмбеддинги только в 0-ом и первом индексе, которые не соответствуют никакому url
(url_host_embeddings_ptls_ids == zeros_row).all(dim=1).nonzero()

tensor([[0],
        [1]])

In [23]:
import sys, os; sys.path.append(os.path.abspath( '..'))

In [24]:

import hydra

In [25]:
hydra.initialize(config_path='conf/trx_custom_embeddings')

/tmp/ipykernel_363467/235621652.py:1: UserWarning:
The version_base parameter is not specified.
Please specify a compatability version level, or None.
Will assume defaults for version 1.1
  hydra.initialize(config_path='conf/trx_custom_embeddings')

hydra.initialize()

In [26]:
cfg = hydra.compose(config_name='ptls_id_to_llm_embedding.yaml', overrides=["+device=cpu"])

In [27]:
d = hydra.utils.instantiate(cfg.url_host_preprocesed)

/path/to/repo/.local/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [32]:
d(196694)

tensor([ 1.8617e-02,  1.3645e-01,  5.5538e-02, -2.3758e-02, -3.5959e-02,
        -2.2530e-02, -2.1419e-02,  1.9846e-02, -3.9278e-02,  4.8616e-01,
        -2.9817e-02,  2.4594e-02, -1.9313e-02, -3.7101e-02,  3.4645e-03,
         4.7599e-01,  2.1399e-02, -4.3298e-01, -5.2009e-02, -2.6571e-02,
        -2.3479e-02, -2.5594e-02,  2.6568e-02,  1.8697e-02,  1.4517e-01,
         6.8349e-01, -2.8599e-01,  1.0387e+00,  3.9317e-02,  2.9678e-02,
         2.3859e-02, -2.9296e-02, -1.3630e-01,  7.3004e-03, -2.0036e-02,
        -2.0599e-02,  2.1640e-02, -2.8106e-02, -2.5282e-02, -2.0887e-01,
        -3.6485e-02, -6.1358e-01, -3.1183e-02, -2.1334e-02, -4.9316e-02,
        -9.2740e-02,  2.7009e-01,  4.4680e-02,  2.4289e-02,  2.7969e-02,
        -1.9067e-01,  3.9060e-02, -3.3784e-02, -1.1686e-01,  9.1262e-04,
        -2.5713e-02, -2.0492e-02,  2.8517e-02,  1.8387e+00,  1.5616e-02,
        -1.3533e-03,  2.9584e-02,  2.3886e+00,  1.0335e-02, -4.4284e-02,
        -4.5088e-01, -7.7603e-01,  3.1989e-01,  1.7814e-02,  2.5080e-01,
        -3.0687e-01,  2.5228e-02,  1.7360e-02,  4.1199e-01,  2.5761e-02,
         1.7898e-02, -1.6370e-01,  2.9823e-02, -9.0036e-03, -6.2065e-02,
         3.2120e-02,  4.0219e-02, -1.9698e-02,  2.3702e-02,  2.7010e-02,
        -2.4893e-01,  2.2936e-01,  2.1820e-02,  1.1785e-01,  4.7221e-02,
         2.4894e+00, -3.1024e-02,  4.0045e-01, -2.8472e-01, -1.4722e-02,
         1.8035e-02, -7.4828e-01,  2.0525e-02,  4.2760e-02, -2.2326e-02,
         1.9045e-02, -2.1828e-02,  2.9616e-02, -2.8233e-02, -2.1553e-02,
        -3.0597e-02,  1.8288e-01,  1.8399e-01,  2.7678e-02, -9.0541e-02,
        -2.4547e-02,  2.8252e-02,  6.3639e-02,  2.1515e-02, -3.0700e-02,
         2.4561e-02,  5.2747e-02, -2.5022e-02, -5.9341e-01,  2.1690e-02,
        -8.7417e-02,  2.5761e-02, -3.6154e-02,  9.5648e-01, -3.2154e-02,
         2.5360e-02,  1.6089e-02,  2.4649e-02, -3.5929e-02, -2.2237e-02,
        -3.3181e-02,  1.2086e-02, -3.6278e-02, -1.9178e-02, -1.9957e-02,
        -2.7921e-02, -3.3941e-02, -1.3241e-01, -8.9327e-02,  3.9914e-02,
        -2.4593e-02,  2.7278e-02, -2.1145e-02,  3.3348e-02, -1.6440e-02,
        -3.1992e-02, -3.5093e-02,  2.1088e-02, -1.7420e-02, -1.5783e-02,
        -1.2345e-02,  2.7108e-02,  5.7524e-02, -2.0074e-02,  1.6515e-02,
        -2.2475e-01,  1.9090e-02,  2.8258e-02, -2.2167e-02, -7.9666e-01,
        -2.4877e-02, -3.8875e-02, -1.5893e-01, -3.9321e-01, -3.5076e-02,
         2.4364e-02, -2.9241e-02, -7.8600e-03, -9.6317e-03,  7.8082e-02,
        -2.2952e-02, -4.0654e-02,  1.8446e-02,  1.9274e-02,  2.0576e-02,
         2.4752e-01, -2.9036e-02, -3.2800e-02,  2.3488e-01, -4.1879e-02,
        -9.1054e-03, -2.5367e-02, -1.3305e-02,  6.7685e-01, -2.8719e-02,
         2.3149e-02, -8.3394e-01, -1.6085e-02,  4.6229e-02,  6.5975e-01,
        -3.0388e-02,  2.0756e-02, -2.7969e-02,  1.9692e-02, -2.6850e-02,
        -2.5676e-02,  4.6324e-02,  9.8147e-01, -1.4105e-01, -2.1480e-02,
         3.9406e-02, -5.0192e-01, -2.1586e-02,  4.2630e-01, -3.4718e-02,
        -2.5258e-01, -3.2383e-02, -3.0416e-02,  1.6498e-02, -2.2975e-02,
        -1.9903e-02, -2.8086e-02,  2.3620e-02, -2.6476e-02, -4.4210e-02,
         1.3792e-02, -2.3034e-02,  1.3217e-02, -8.7099e-03, -1.9973e-02,
        -4.5507e-02, -3.1860e-01,  1.5226e-01,  1.6268e-02, -3.6552e-02,
         1.7561e-02,  5.9375e-02,  1.3250e-02, -6.4011e-02, -4.1933e-02,
        -1.8087e-02, -4.1417e-02,  3.6033e-02,  5.5611e-01, -3.0592e-02,
         2.3059e-02, -3.0141e-01, -1.2633e+00,  2.9524e-02, -2.3042e-02,
         5.7489e-03,  1.2904e-02, -3.9689e-02,  4.8987e-02, -3.3527e-02,
         1.1194e-01, -1.3573e-01,  3.3471e-02,  1.8333e-01, -1.5808e-02,
        -3.9496e-02, -1.8635e-02, -5.8882e-01, -2.4649e-02, -2.9155e-02,
         6.8780e-02], grad_fn=<EmbeddingBackward0>)

In [37]:
url_encoding_map_df[url_encoding_map_df['url_host_preprocesed'] == 196694]

       _orig_url_host_preprocesed  url_host_preprocesed
196692              adminstanovoe                196694

In [44]:
len(d.ptls_item_id_to_pretrained_embedding_id)

199685

In [46]:
d.ptls_item_id_to_pretrained_embedding_id[196694]

tensor(196694)

In [35]:
d

PretrainedEmbeddings(
  (embedding_layer): Embedding(196695, 256)
)

In [43]:
d.ptls_item_id_to_pretrained_embedding_id[123]

tensor(123)