In [1]:
import pandas as pd

In [3]:
!ls data

client_id_map.parquet
coles_avg_pool_model_embeddings.pickle
coles__batch_size_48__split_count_2__150_epoches_embeddings.pickle
graphs
mles_model_small_batch_2_embeddings
mles_model_small_batch_2_embeddings.pickle
small_group_mapping.csv
test_ids_file.csv
test_trx_file.parquet
train_target.csv
train_trx_file.parquet
transactions_test.csv
transactions_train.csv

In [5]:
train_trx_df = pd.read_parquet('data/train_trx_file.parquet')

In [6]:
train_trx_df.head()

,client_id,event_time,amount_rur,trans_date,small_group,trx_count,target,encoded_client_id
0,10096,"[7.0, 7.0, 7.0, 8.0, 9.0, 10.0, 11.0, 11.0, 12...","[3.011654834097806, 3.7870718400053156, 4.2543...","[728, 728, 728, 720, 717, 711, 703, 703, 636, ...","[3, 8, 2, 2, 3, 3, 3, 4, 2, 3, 4, 8, 3, 2, 30,...",1049,0.0,110
1,10146,"[4.0, 8.0, 9.0, 22.0, 26.0, 27.0, 27.0, 34.0, ...","[3.3016348400359656, 2.24834007814165, 2.12525...","[723, 720, 717, 702, 623, 686, 686, 649, 604, ...","[2, 5, 6, 21, 12, 12, 21, 2, 2, 2, 3, 2, 2, 18...",741,3.0,166
2,10351,"[9.0, 13.0, 14.0, 14.0, 14.0, 15.0, 16.0, 16.0...","[2.516566802515869, 2.634618923016327, 2.92138...","[717, 690, 722, 722, 722, 714, 706, 706, 706, ...","[3, 2, 2, 4, 8, 2, 5, 3, 2, 2, 3, 2, 8, 2, 2, ...",876,3.0,394
3,1059,"[6.0, 8.0, 9.0, 9.0, 9.0, 10.0, 11.0, 12.0, 12...","[4.013803119089597, 4.418153624889916, 3.29127...","[729, 720, 717, 717, 717, 711, 703, 636, 636, ...","[13, 11, 4, 11, 2, 13, 2, 4, 11, 2, 2, 13, 4, ...",742,1.0,658
4,10765,"[48.0, 51.0, 52.0, 55.0, 57.0, 59.0, 59.0, 60....","[3.2582503723422223, 2.7566498709382725, 2.300...","[643, 644, 512, 698, 684, 639, 639, 663, 499, ...","[2, 2, 2, 2, 2, 2, 6, 2, 2, 2, 2, 78, 2, 2, 12...",881,1.0,853

In [7]:
train_item_ids = {el for seq in train_trx_df['small_group'] for el in seq}

In [8]:
train_item_ids

{2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205}

In [10]:
train_item_ids == set(range(2, 186))

False

In [11]:
test_trx_df = pd.read_parquet('data/test_trx_file.parquet')
test_trx_df.head()

,client_id,event_time,amount_rur,trans_date,small_group,trx_count,target,encoded_client_id
0,11841,"[1.0, 1.0, 3.0, 5.0, 6.0, 7.0, 8.0, 8.0, 8.0, ...","[1.4831941858598499, 3.2896324733190014, 1.662...","[727, 727, 724, 726, 729, 728, 720, 720, 720, ...","[40, 15, 40, 2, 70, 18, 44, 66, 8, 40, 2, 3, 4...",1083,0,2049
1,13610,"[1.0, 2.0, 2.0, 2.0, 3.0, 6.0, 8.0, 9.0, 14.0,...","[3.5934417661807956, 3.1602716605521475, 3.720...","[727, 725, 725, 725, 724, 729, 720, 717, 722, ...","[2, 2, 11, 30, 2, 4, 2, 2, 5, 2, 2, 4, 2, 4, 2...",904,3,4015
2,14369,"[6.0, 12.0, 13.0, 14.0, 15.0, 15.0, 18.0, 18.0...","[3.114581407392372, 2.9042198730478836, 3.2409...","[729, 636, 690, 722, 714, 714, 693, 693, 721, ...","[4, 40, 2, 62, 3, 5, 5, 2, 19, 3, 3, 5, 4, 2, ...",782,2,4857
3,16076,"[1.0, 3.0, 4.0, 4.0, 8.0, 10.0, 11.0, 12.0, 13...","[2.223217157610473, 6.1641649688578815, 2.6346...","[727, 724, 723, 723, 720, 711, 703, 636, 690, ...","[3, 19, 4, 29, 4, 4, 4, 4, 3, 4, 7, 35, 29, 20...",890,0,6754
4,17506,"[5.0, 9.0, 10.0, 10.0, 10.0, 15.0, 15.0, 15.0,...","[3.551196598938362, 4.264438892446495, 2.85578...","[726, 717, 711, 711, 711, 714, 714, 714, 706, ...","[17, 74, 12, 2, 6, 7, 3, 8, 7, 7, 25, 52, 2, 7...",1015,0,8343

In [12]:
test__item_ids = {el for seq in test_trx_df['small_group'] for el in seq}

In [13]:
test__item_ids <= train_item_ids

True

In [18]:
train_item_ids == set(range(2, 206))

True

In [22]:
train_item_ids - test__item_ids

{182, 187, 192, 194, 195, 196, 197, 198, 199, 201, 202, 203, 204, 205}

In [23]:
test__item_ids - train_item_ids

set()

In [ ]:
len(tra)

In [1]:
import torch

In [2]:
!ls data/graphs/weighted

client_id2full_graph_id.pt   similarity_matrix.npy
client_id2train_graph_id.pt  train_graph.bin
full_graph.bin		     train_graph_id2client_id__dict.pt
item_id2full_graph_id.pt     train_node_labeled_ids.pt
item_id2train_graph_id.pt    train_node_labels.pt

In [4]:
torch.load('data/graphs/weighted/train_graph_id2client_id__dict.pt')

{0: 0,
 1: 1,
 2: 2,
 3: 3,
 4: 4,
 5: 5,
 6: 6,
 7: 7,
 8: 8,
 9: 9,
 10: 10,
 11: 11,
 12: 12,
 13: 13,
 14: 14,
 15: 15,
 16: 16,
 17: 17,
 18: 18,
 19: 19,
 20: 20,
 21: 21,
 22: 23,
 23: 24,
 24: 25,
 25: 26,
 26: 27,
 27: 28,
 28: 29,
 29: 30,
 30: 32,
 31: 33,
 32: 34,
 33: 35,
 34: 36,
 35: 37,
 36: 38,
 37: 39,
 38: 40,
 39: 41,
 40: 42,
 41: 43,
 42: 44,
 43: 45,
 44: 46,
 45: 47,
 46: 48,
 47: 49,
 48: 50,
 49: 51,
 50: 52,
 51: 53,
 52: 54,
 53: 55,
 54: 56,
 55: 57,
 56: 58,
 57: 59,
 58: 60,
 59: 61,
 60: 62,
 61: 63,
 62: 65,
 63: 66,
 64: 67,
 65: 68,
 66: 69,
 67: 70,
 68: 71,
 69: 72,
 70: 73,
 71: 74,
 72: 75,
 73: 76,
 74: 77,
 75: 78,
 76: 79,
 77: 80,
 78: 81,
 79: 82,
 80: 83,
 81: 84,
 82: 85,
 83: 86,
 84: 87,
 85: 89,
 86: 90,
 87: 91,
 88: 92,
 89: 93,
 90: 94,
 91: 95,
 92: 96,
 93: 98,
 94: 99,
 95: 100,
 96: 101,
 97: 102,
 98: 103,
 99: 104,
 100: 105,
 101: 106,
 102: 107,
 103: 108,
 104: 109,
 105: 110,
 106: 111,
 107: 112,
 108: 113,
 109: 114,
 110: 115,
 111: 116,
 112: 117,
 113: 119,
 114: 120,
 115: 121,
 116: 122,
 117: 123,
 118: 124,
 119: 125,
 120: 126,
 121: 127,
 122: 128,
 123: 129,
 124: 130,
 125: 131,
 126: 132,
 127: 133,
 128: 134,
 129: 135,
 130: 136,
 131: 137,
 132: 138,
 133: 139,
 134: 140,
 135: 141,
 136: 142,
 137: 143,
 138: 144,
 139: 145,
 140: 146,
 141: 148,
 142: 149,
 143: 150,
 144: 151,
 145: 153,
 146: 154,
 147: 155,
 148: 156,
 149: 158,
 150: 159,
 151: 160,
 152: 161,
 153: 162,
 154: 163,
 155: 164,
 156: 165,
 157: 166,
 158: 167,
 159: 168,
 160: 169,
 161: 170,
 162: 171,
 163: 172,
 164: 173,
 165: 174,
 166: 175,
 167: 176,
 168: 178,
 169: 179,
 170: 180,
 171: 181,
 172: 182,
 173: 183,
 174: 184,
 175: 185,
 176: 186,
 177: 187,
 178: 188,
 179: 189,
 180: 190,
 181: 191,
 182: 192,
 183: 193,
 184: 194,
 185: 195,
 186: 196,
 187: 197,
 188: 198,
 189: 200,
 190: 201,
 191: 202,
 192: 203,
 193: 204,
 194: 205,
 195: 206,
 196: 207,
 197: 208,
 198: 209,
 199: 210,
 200: 211,
 201: 212,
 202: 213,
 203: 214,
 204: 215,
 205: 216,
 206: 217,
 207: 218,
 208: 219,
 209: 220,
 210: 221,
 211: 222,
 212: 223,
 213: 224,
 214: 225,
 215: 226,
 216: 227,
 217: 228,
 218: 229,
 219: 230,
 220: 231,
 221: 232,
 222: 233,
 223: 234,
 224: 235,
 225: 236,
 226: 237,
 227: 238,
 228: 239,
 229: 240,
 230: 241,
 231: 242,
 232: 243,
 233: 244,
 234: 245,
 235: 246,
 236: 247,
 237: 248,
 238: 249,
 239: 250,
 240: 251,
 241: 252,
 242: 253,
 243: 254,
 244: 255,
 245: 256,
 246: 257,
 247: 258,
 248: 259,
 249: 260,
 250: 261,
 251: 262,
 252: 263,
 253: 264,
 254: 265,
 255: 266,
 256: 267,
 257: 268,
 258: 269,
 259: 270,
 260: 271,
 261: 272,
 262: 273,
 263: 274,
 264: 275,
 265: 276,
 266: 277,
 267: 278,
 268: 279,
 269: 280,
 270: 281,
 271: 282,
 272: 283,
 273: 284,
 274: 285,
 275: 286,
 276: 287,
 277: 288,
 278: 290,
 279: 291,
 280: 292,
 281: 293,
 282: 294,
 283: 295,
 284: 296,
 285: 297,
 286: 298,
 287: 299,
 288: 300,
 289: 301,
 290: 302,
 291: 303,
 292: 305,
 293: 306,
 294: 307,
 295: 308,
 296: 309,
 297: 310,
 298: 311,
 299: 312,
 300: 313,
 301: 314,
 302: 315,
 303: 316,
 304: 317,
 305: 318,
 306: 319,
 307: 320,
 308: 321,
 309: 322,
 310: 323,
 311: 324,
 312: 325,
 313: 326,
 314: 328,
 315: 329,
 316: 330,
 317: 331,
 318: 332,
 319: 333,
 320: 334,
 321: 335,
 322: 336,
 323: 337,
 324: 338,
 325: 339,
 326: 340,
 327: 342,
 328: 343,
 329: 344,
 330: 345,
 331: 346,
 332: 347,
 333: 348,
 334: 349,
 335: 350,
 336: 351,
 337: 352,
 338: 353,
 339: 354,
 340: 355,
 341: 356,
 342: 357,
 343: 358,
 344: 359,
 345: 360,
 346: 361,
 347: 362,
 348: 363,
 349: 365,
 350: 366,
 351: 367,
 352: 368,
 353: 369,
 354: 370,
 355: 371,
 356: 372,
 357: 373,
 358: 374,
 359: 375,
 360: 376,
 361: 377,
 362: 378,
 363: 379,
 364: 380,
 365: 381,
 366: 382,
 367: 383,
 368: 384,
 369: 385,
 370: 386,
 371: 387,
 372: 388,
 373: 389,
 374: 390,
 375: 391,
 376: 392,
 377: 393,
 378: 394,
 379: 395,
 380: 396,
 381: 397,
 382: 398,
 383: 399,
 384: 401,
 385: 402,
 386: 403,
 387: 404,
 388: 405,
 389: 406,
 390: 407,
 391: 408,
 392: 409,
 393: 410,
 394: 411,
 395: 412,
 396: 413,
 397: 414,
 398: 415,
 399: 416,
 400: 417,
 401: 418,
 402: 419,
 403: 420,
 404: 421,
 405: 422,
 406: 423,
 407: 424,
 408: 425,
 409: 426,
 410: 428,
 411: 430,
 412: 431,
 413: 433,
 414: 434,
 415: 435,
 416: 436,
 417: 437,
 418: 438,
 419: 439,
 420: 440,
 421: 441,
 422: 442,
 423: 443,
 424: 444,
 425: 445,
 426: 446,
 427: 447,
 428: 448,
 429: 449,
 430: 451,
 431: 452,
 432: 454,
 433: 455,
 434: 456,
 435: 457,
 436: 458,
 437: 459,
 438: 460,
 439: 461,
 440: 462,
 441: 463,
 442: 464,
 443: 465,
 444: 466,
 445: 467,
 446: 468,
 447: 469,
 448: 470,
 449: 471,
 450: 472,
 451: 473,
 452: 474,
 453: 475,
 454: 476,
 455: 477,
 456: 478,
 457: 479,
 458: 480,
 459: 481,
 460: 482,
 461: 483,
 462: 484,
 463: 485,
 464: 486,
 465: 487,
 466: 488,
 467: 489,
 468: 490,
 469: 491,
 470: 492,
 471: 493,
 472: 494,
 473: 495,
 474: 496,
 475: 497,
 476: 498,
 477: 499,
 478: 500,
 479: 501,
 480: 502,
 481: 503,
 482: 504,
 483: 505,
 484: 506,
 485: 507,
 486: 508,
 487: 509,
 488: 510,
 489: 512,
 490: 514,
 491: 515,
 492: 516,
 493: 517,
 494: 518,
 495: 519,
 496: 520,
 497: 521,
 498: 522,
 499: 523,
 500: 524,
 501: 525,
 502: 526,
 503: 527,
 504: 528,
 505: 529,
 506: 530,
 507: 532,
 508: 533,
 509: 534,
 510: 535,
 511: 536,
 512: 537,
 513: 538,
 514: 539,
 515: 540,
 516: 541,
 517: 542,
 518: 543,
 519: 544,
 520: 545,
 521: 546,
 522: 547,
 523: 548,
 524: 549,
 525: 550,
 526: 551,
 527: 552,
 528: 554,
 529: 555,
 530: 556,
 531: 557,
 532: 558,
 533: 559,
 534: 560,
 535: 561,
 536: 562,
 537: 563,
 538: 564,
 539: 565,
 540: 566,
 541: 567,
 542: 568,
 543: 569,
 544: 570,
 545: 571,
 546: 572,
 547: 573,
 548: 574,
 549: 575,
 550: 576,
 551: 577,
 552: 578,
 553: 579,
 554: 580,
 555: 581,
 556: 582,
 557: 583,
 558: 584,
 559: 585,
 560: 586,
 561: 587,
 562: 588,
 563: 589,
 564: 590,
 565: 591,
 566: 592,
 567: 593,
 568: 594,
 569: 595,
 570: 596,
 571: 597,
 572: 598,
 573: 599,
 574: 600,
 575: 601,
 576: 602,
 577: 603,
 578: 604,
 579: 605,
 580: 606,
 581: 607,
 582: 608,
 583: 609,
 584: 610,
 585: 611,
 586: 612,
 587: 613,
 588: 614,
 589: 615,
 590: 616,
 591: 617,
 592: 618,
 593: 619,
 594: 620,
 595: 621,
 596: 622,
 597: 623,
 598: 624,
 599: 625,
 600: 626,
 601: 627,
 602: 628,
 603: 629,
 604: 630,
 605: 631,
 606: 632,
 607: 633,
 608: 635,
 609: 636,
 610: 637,
 611: 638,
 612: 639,
 613: 640,
 614: 641,
 615: 642,
 616: 643,
 617: 644,
 618: 645,
 619: 646,
 620: 647,
 621: 648,
 622: 649,
 623: 650,
 624: 651,
 625: 652,
 626: 653,
 627: 654,
 628: 655,
 629: 656,
 630: 657,
 631: 658,
 632: 659,
 633: 660,
 634: 661,
 635: 662,
 636: 663,
 637: 664,
 638: 665,
 639: 666,
 640: 667,
 641: 668,
 642: 669,
 643: 670,
 644: 671,
 645: 672,
 646: 673,
 647: 674,
 648: 675,
 649: 676,
 650: 677,
 651: 678,
 652: 679,
 653: 680,
 654: 681,
 655: 682,
 656: 683,
 657: 684,
 658: 685,
 659: 686,
 660: 687,
 661: 688,
 662: 689,
 663: 690,
 664: 691,
 665: 692,
 666: 693,
 667: 695,
 668: 696,
 669: 697,
 670: 698,
 671: 699,
 672: 700,
 673: 701,
 674: 702,
 675: 703,
 676: 704,
 677: 705,
 678: 706,
 679: 707,
 680: 708,
 681: 709,
 682: 710,
 683: 711,
 684: 712,
 685: 713,
 686: 714,
 687: 715,
 688: 716,
 689: 718,
 690: 719,
 691: 720,
 692: 721,
 693: 722,
 694: 723,
 695: 724,
 696: 725,
 697: 726,
 698: 727,
 699: 728,
 700: 729,
 701: 730,
 702: 731,
 703: 732,
 704: 733,
 705: 734,
 706: 735,
 707: 736,
 708: 737,
 709: 738,
 710: 739,
 711: 740,
 712: 741,
 713: 742,
 714: 743,
 715: 744,
 716: 745,
 717: 746,
 718: 747,
 719: 748,
 720: 749,
 721: 750,
 722: 751,
 723: 752,
 724: 753,
 725: 754,
 726: 755,
 727: 756,
 728: 757,
 729: 758,
 730: 759,
 731: 760,
 732: 761,
 733: 762,
 734: 763,
 735: 764,
 736: 765,
 737: 766,
 738: 767,
 739: 768,
 740: 769,
 741: 770,
 742: 771,
 743: 772,
 744: 773,
 745: 774,
 746: 775,
 747: 776,
 748: 777,
 749: 778,
 750: 779,
 751: 781,
 752: 782,
 753: 783,
 754: 784,
 755: 785,
 756: 786,
 757: 787,
 758: 788,
 759: 789,
 760: 790,
 761: 791,
 762: 792,
 763: 793,
 764: 794,
 765: 795,
 766: 796,
 767: 797,
 768: 798,
 769: 799,
 770: 801,
 771: 802,
 772: 803,
 773: 804,
 774: 805,
 775: 806,
 776: 807,
 777: 809,
 778: 810,
 779: 811,
 780: 812,
 781: 813,
 782: 814,
 783: 815,
 784: 816,
 785: 817,
 786: 818,
 787: 819,
 788: 820,
 789: 821,
 790: 822,
 791: 823,
 792: 824,
 793: 825,
 794: 826,
 795: 827,
 796: 828,
 797: 829,
 798: 830,
 799: 831,
 800: 832,
 801: 833,
 802: 834,
 803: 835,
 804: 836,
 805: 837,
 806: 839,
 807: 840,
 808: 842,
 809: 843,
 810: 844,
 811: 845,
 812: 846,
 813: 847,
 814: 848,
 815: 849,
 816: 850,
 817: 851,
 818: 852,
 819: 853,
 820: 854,
 821: 855,
 822: 856,
 823: 857,
 824: 858,
 825: 859,
 826: 860,
 827: 861,
 828: 862,
 829: 863,
 830: 864,
 831: 865,
 832: 866,
 833: 867,
 834: 868,
 835: 869,
 836: 870,
 837: 871,
 838: 873,
 839: 874,
 840: 875,
 841: 876,
 842: 877,
 843: 878,
 844: 879,
 845: 880,
 846: 881,
 847: 882,
 848: 883,
 849: 884,
 850: 885,
 851: 886,
 852: 887,
 853: 888,
 854: 889,
 855: 890,
 856: 891,
 857: 892,
 858: 893,
 859: 894,
 860: 895,
 861: 896,
 862: 897,
 863: 898,
 864: 899,
 865: 901,
 866: 902,
 867: 903,
 868: 904,
 869: 905,
 870: 906,
 871: 907,
 872: 908,
 873: 909,
 874: 910,
 875: 911,
 876: 912,
 877: 913,
 878: 914,
 879: 915,
 880: 916,
 881: 917,
 882: 918,
 883: 920,
 884: 921,
 885: 922,
 886: 923,
 887: 924,
 888: 925,
 889: 926,
 890: 927,
 891: 928,
 892: 929,
 893: 930,
 894: 932,
 895: 933,
 896: 934,
 897: 935,
 898: 936,
 899: 937,
 900: 938,
 901: 939,
 902: 940,
 903: 941,
 904: 942,
 905: 943,
 906: 944,
 907: 945,
 908: 946,
 909: 947,
 910: 948,
 911: 949,
 912: 950,
 913: 951,
 914: 952,
 915: 953,
 916: 954,
 917: 955,
 918: 956,
 919: 957,
 920: 958,
 921: 959,
 922: 960,
 923: 961,
 924: 962,
 925: 963,
 926: 964,
 927: 965,
 928: 966,
 929: 967,
 930: 968,
 931: 969,
 932: 970,
 933: 971,
 934: 972,
 935: 973,
 936: 975,
 937: 976,
 938: 977,
 939: 978,
 940: 979,
 941: 980,
 942: 981,
 943: 982,
 944: 983,
 945: 984,
 946: 985,
 947: 986,
 948: 987,
 949: 988,
 950: 989,
 951: 990,
 952: 991,
 953: 992,
 954: 993,
 955: 994,
 956: 995,
 957: 996,
 958: 997,
 959: 998,
 960: 999,
 961: 1000,
 962: 1001,
 963: 1002,
 964: 1003,
 965: 1004,
 966: 1005,
 967: 1006,
 968: 1007,
 969: 1008,
 970: 1009,
 971: 1010,
 972: 1011,
 973: 1012,
 974: 1013,
 975: 1014,
 976: 1015,
 977: 1016,
 978: 1017,
 979: 1018,
 980: 1019,
 981: 1021,
 982: 1022,
 983: 1023,
 984: 1024,
 985: 1025,
 986: 1026,
 987: 1027,
 988: 1028,
 989: 1029,
 990: 1030,
 991: 1031,
 992: 1032,
 993: 1033,
 994: 1034,
 995: 1035,
 996: 1036,
 997: 1037,
 998: 1038,
 999: 1039,
 ...}

In [6]:
import pandas as pd

In [7]:
train_trx_df = pd.read_parquet('data/train_trx_file.parquet')

In [9]:
len(train_trx_df['encoded_client_id'])

47000